### ISSUE TITLE
rate_limit conditional write example does not work

### ISSUE THREAD

**Issue by joedj** [applerom/aws-s3-conditional-requests-examples#1]
Unfortunately, the conditional write example rate limiter does not work.

`PutObject` does not support `If-Match`.  It only supports `If-None-Match`, and the only valid value is `If-None-Match: *`, which means "do not create the object if it already exists".  This can't be used to implement an atomic read-modify-update, in this way.

Ref:
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/conditional-requests.html
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html

**Comment by applerom** [comment]
Thanks for pointing out the limitations of `PutObject`. 

The `rate_limiter.py` example has been reworked to work within the S3 constraints. Instead of atomic read-modify-update, it now uses S3 objects as query tokens in a temporary window using `If-None-Match`.

A section has been added to the README describing these limitations. And the example is now not a true atomic rate limiter, but just a version of how to use conditional queries with what S3 allows.

**Comment by applerom** [comment]
Closing this issue as it's been addressed in the latest updates. Thanks again for your help!
